#!/bin/bash
#VIRTUALENV=/home/jarvis/venv
if [ ! -z $VIRTUALENV ]; then
    source $VIRTUALENV/bin/activate
fi

CWD=$(readlink -f $0)
CWD=$(dirname "$CWD")

if [ ! -r "${CWD}/bot.cfg" ]; then
	echo "'bot.cfg' is missing. Have you copied 'bot.cfg.example'?"
	exit 2
fi

case $1 in
	start)
		[ ! -d "${CWD}/logs" ] && mkdir "${CWD}/logs"

		python "${CWD}/willie/willie.py" -c "${CWD}/bot.cfg" --fork
		;;
	stop)
		python "${CWD}/willie/willie.py" -c "${CWD}/bot.cfg" --quit
		;;

	restart)
		"$0" stop
		sleep 2
		"$0" start
		;;

	reload)
		echo "Not supported by script."
		exit 2
		;;

	*)
		echo "Unknown command. Please give 'start', 'stop' or 'restart'."
		exit 1
		;;
esac
